version: '3.8'

services:
  openvpn:
    cap_add:
      - NET_ADMIN
    image: kylemanna/openvpn:edge
    container_name: openvpn
    ports:
      - "1194:1194/udp"
    restart: always
    volumes:
      - ovpn-data:/etc/openvpn
    environment:
      - VIRTUAL_HOST=${SITE}
      - LETSENCRYPT_HOST=${SITE}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
    networks:
      - nginx-proxy
      
volumes:
  ovpn-data:
    external: true

networks:
  nginx-proxy:
    external: true 