version: "3.8"

services:
  nginx-proxy:
    build: ./proxy
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "html:/usr/share/nginx/html"
      - "dhparam:/etc/nginx/dhparam"
      - "vhost:/etc/nginx/vhost.d"
      - "certs:/etc/nginx/certs:ro"
      - "/run/docker.sock:/tmp/docker.sock:ro"
    networks: 
      - "network-nginx-proxy"

  letsencrypt:
    image: "jrcs/letsencrypt-nginx-proxy-companion:latest"
    container_name: letsencrypt-helper
    volumes_from:
      - "nginx-proxy"
    volumes:
      - "certs:/etc/nginx/certs:rw"
      - "/run/docker.sock:/var/run/docker.sock:ro"
    environment:
      NGINX_PROXY_CONTAINER: "nginx-proxy"
      DEFAULT_EMAIL: "${LETSENCRYPT_EMAIL}"
    restart: "always"
    depends_on:
      - "nginx-proxy"
    networks: 
      - "network-nginx-proxy"
      
volumes:
  certs:
  html:
  vhost:
  dhparam:

networks:
  network-nginx-proxy:
  external: true