version: "3.9"
    
services:

  db:
    image: mysql:8
    container_name: wp_db
    volumes:
      - wordpress_db:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_USER_PASSWORD}
    command: '--default-authentication-plugin=mysql_native_password'
    
  wordpress:
    image: wordpress:latest
    container_name: wp_app
    volumes:
      - wordpress_data:/var/www/html
    restart: always
    depends_on:
      - db
    environment:
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_USER=${DB_USER}
      - WORDPRESS_DB_PASSWORD=${DB_USER_PASSWORD}
      - WORDPRESS_DB_NAME=${DB_NAME}

  web:
    build: ./web
    depends_on:
      - wordpress
    container_name: wp_web
    restart: unless-stopped
    volumes:
      - wordpress_data:/var/www/html
      - ./web:/etc/nginx/conf.d
    environment:
      - VIRTUAL_HOST=${SITE}
      - LETSENCRYPT_HOST=${SITE}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
    networks:
      - nginx-proxy
      - default
      
networks:
  nginx-proxy:
    external: true

volumes:
  wordpress_db: {}
  wordpress_data: {}

