services:
  traefik:
    deploy:
      replicas: 0
      
  erpnext-nginx:
    environment:
      - VIRTUAL_HOST=${SITES}
      - LETSENCRYPT_HOST=${SITES}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
    networks:
      - default
      - network-nginx-proxy
      
networks:
  network-nginx-proxy:
    external: true