version: '3'

services:
  db:
    image: postgres:latest
    restart: always
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=$(DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}

  redis:
    image: redis:latest
    container_name: "nc-redis"
    restart: always

  app:
    image: nextcloud:production-fpm
    container_name: "nc-main"
    restart: always
    volumes:
      - nextcloud:/var/www/html
    environment:
      - POSTGRES_HOST=db
      - REDIS_HOST=redis
      - POSTGRES_PASSWORD=$(DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
    depends_on:
      - db
      - redis

  web:
    build: ./web
    container_name: "nc-web"
    restart: always
    volumes:
      - nextcloud:/var/www/html:ro
    environment:
      - VIRTUAL_HOST=${SITE}
      - LETSENCRYPT_HOST=${SITE}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
    depends_on:
      - app
    networks:
      - network-nginx-proxy
      - default

volumes:
  db:
  nextcloud:

networks:
  network-nginx-proxy:
    external: true